Feat/display card list
CharlesSquirel/fischkapp pull request #23
Opened 2023-10-10 10:06 UTC by CharlesSquirel

2023-10-10 14:11 UTC, Sumick requested changes
There are unrelated files in this PR. Please, pull main first, and leave only task relevant files.

2023-10-10 16:09 UTC, CharlesSquirel commented
Is there any chance for checking my test refactoring, even if it is not related to the task? Or it will be reviewed at the QA stage?

2023-10-11 21:51 UTC, Sumick approved these changes
Tests look nice - good job! I've found few things we should improve before merging

2023-10-11 21:51 UTC, Sumick commented on src/App.tsx
> +    setFlashCards(cards);
**nitpick:** This function is missing error handling

2023-10-11 21:51 UTC, Sumick commented on src/components/Card/CardEdit.tsx
> +      await getAllCards();
**nitpick:** You'd have to add these `if` all the time adding complexity to your codebase - let's fix it, so you don't have to do this.

2023-10-11 21:51 UTC, Sumick commented on src/components/services/api/api.ts
> +    return data;
**nitpick:** This function is missing return type.

2023-10-11 21:51 UTC, Sumick commented on src/components/services/types/types.ts
> +  getAllCards?: () => {};
**nitpick:** Why optional?

2023-10-11 21:51 UTC, Sumick commented on src/tests/App.test.tsx
> +  //   expect(frontCardInput).toEqual(newValue)
**nitpick:** comment to remove

2023-10-12 11:41 UTC, merged